openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Finstat Internal API'
  description: Get data about comapanies in Slovakia

paths:
  /companies:
    parameters:
        -   name: order
            in: query
            description: Order by
            required: false
            schema:
                type: string
                enum: [name, revenue, profits, assets_total, liabilities_total, capital]
        -   name: order_direction
            in: query
            description: Order direction
            required: false
            schema:
                type: string
                enum: [asc, desc]
        -   name: per_page
            in: query
            description: Number of items per page
            required: false
            schema:
                type: integer
                minimum: 1
                maximum: 100
        -   name: page
            in: query
            description: Page number
            required: false
            schema:
                type: integer
                minimum: 1
        -   name: search_query
            in: query
            description: Search query
            required: false
            schema:
                type: string
        -   name: revenue_min
            in: query
            description: Revenue min
            required: false
            schema:
                type: integer
        -   name: revenue_max
            in: query
            description: Revenue max
            required: false
            schema:
                type: integer
        -   name: profits_min
            in: query
            description: Profits min
            required: false
            schema:
                type: integer
        -   name: profits_max
            in: query
            description: Profits max
            required: false
            schema:
                type: integer
    get:
      summary: Get list of companies
      responses:
        '200':
            description: List of companies
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            meta:
                                $ref: '#/components/schemas/PaginationMeta'
                            data:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Company'
components:
  schemas:
    Ico:
      description: The unique identifier of a tax entity
      type: string
    Company:
      type: object
      properties:
        name:
          type: string
        official_id:
          type: string
        ico:
            $ref: '#/components/schemas/Ico'
        dic:
            type: string
        address:
            type: object
            properties:
              street:
                type: string
              city:
                type: string
              zip:
                type: string
              country:
                type: string
    PaginationMeta:
        type: object
        properties:
            total:
                type: integer
            per_page:
                type: integer
            current_page:
                type: integer
            last_page:
                type: integer
            from:
                type: integer
            to:
                type: integer
            path:
                type: string
                description: Path to the endpoint
    PaginationLinks:
        type: object
        properties:
            first:
                type: string
                description: Link to the first page
            last:
                type: string
                description: Link to the last page
            prev:
                type: string
                description: Link to the previous page
            next:
                type: string
                description: Link to the next page
